Added ros2cs and ROS2 For Unity following their open source release
fkromer/awesome-ros2 pull request #31
Opened 2021-08-23 13:02 UTC by adamdbrw

2021-08-23 21:27 UTC, adamdbrw commented
Context of the release: https://www.linkedin.com/posts/robotec-ai_open-source-release-of-ros2-for-unity-robotecai-activity-6835611979130953728-t2dn

2021-08-24 17:00 UTC, fkromer requested changes

2021-08-25 08:27 UTC, adamdbrw commented on readme.md
> +- [ROS2 For Unity](https://github.com/RobotecAI/ros2-for-unity) - An asset package which enables high-performance communication between Unity3D simulations and ROS2 ecosystem. ![ros2-for-unity](https
Done!

2021-08-25 13:40 UTC, merged

2021-08-25 13:40 UTC, fkromer commented
@adamdbrw Thanks!